### ISSUE TITLE
DTO

### ISSUE THREAD

**Issue by itgroupa** [elmario89/fake-instagram#1]
server-nest/src/users/dto/create-user.dto.ts

сервисы должны принимать DTO объкты, DTO объекты не валидируют параметры их задача передовать
Валидацией параметров на входе занимаются View модели

Можно сделать так

Во View модели сделать метод, который вернёт Dto модель и уже его передовать в сервисы

**Comment by elmario89** [comment]
Dto doesn't validate params, decorator @ApiProperty only serves swagger ui.
